name: "Template Repository Rename"
description: ""
branding:
  icon: "settings"
  color: "white"
inputs:
  github-token:
    description: "GitHub token"
    default: ${{ github.token }}
  from-name:
    description: "From name"
  to-name:
    description: "To name"
  commit-message:
    description: "Commit message"
    default: "Renamed"

runs:
  using: docker
  image: Dockerfile
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    FROM_NAME: ${{ inputs.from-name }}
    TO_NAME: ${{ inputs.to-name }}
    COMMIT_MESSAGE: ${{ inputs.commit-message }}
