name: "Rename Template Repository"
description: "Replace & Rename files and directories of a repository created from a template repository"
branding:
  icon: "copy"
  color: "white"
inputs:
  from-name:
    description: "Project name from the template repository"
  to-name:
    description: "New project name"
  paths-ignore:
    description: "Paths to ignore"
  commit-message:
    description: "Commit message"
    default: "rename"
  github-token:
    description: "GitHub token"
  default-github-token:
    description: "Default gitHub token"
    default: ${{ github.token }}
  pr-branch:
    description: "PR head branch"
    default: "template-rename"
  pr-base-branch:
    description: "PR base branch"
  pr-title:
    description: "PR title"
    default: "Template rename"
  pr-labels:
    description: "PR labels"
  dry-run:
    description: "Dry run or not"
    default: "false"
runs:
  using: "node16"
  main: "dist/index.js"
